webui/urls.py
from django.conf.urls.defaults import *
from webui.export import views as ex_views
from webui.inventory import views as in_views
import os

# everything is done through
# the django admin interface!
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns("",
    (r'^assets/(?P<path>.*)$', "django.views.static.serve",
        {"document_root": os.path.dirname(__file__) + "/static"}),

    (r'^graphs/(?P<path>.*)$', "django.views.static.serve",
        {"document_root": os.path.dirname(__file__) + "/graphs"}),
    
	(r'^favicon\.ico$', 'django.views.generic.simple.redirect_to',
		{'url': '/assets/favicon.ico'}),
    
    # exporting is magic!
	(r'^(?P<app_label>.+?)/(?P<model_name>.+?)/export/excel/$', ex_views.to_excel),
	(r'^(?P<app_label>.+?)/(?P<model_name>.+?)/export/print/$', in_views.to_print),
	(r'^export/$', ex_views.export),
     
    # send sms
	(r'^send_sms/$', 'inventory.views.send_sms'),
	
	# various google maps
	(r'^map/entries/$', in_views.map_entries),

    # redirect everything else to admin
    (r'^(.*)', admin.site.root),
)

webui/inventory/models.py
#!/usr/bin/env python
# vim: noet

from django.db import models
from django.contrib.auth import models as auth_models
from django.core.exceptions import ObjectDoesNotExist 
from webui.utils import otp_code, woreda_code 


class Monitor(models.Model):
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	alias = models.CharField(max_length=16, unique=True, help_text="Abbreviated name, lowercase letters")
	phone = models.CharField(max_length=30, blank=True, help_text="e.g., +251912555555")
	email = models.EmailField(blank=True)
	incoming_messages = models.PositiveIntegerField(help_text="The number of messages that uniSMS has received from this Monitor")
	
	class Meta:
		verbose_name = "Field Monitor"
		ordering = ['last_name']
	
	# the string version of monitors
	# now contains only their name
	def __unicode__(self):
		return "%s %s" %\
			(self.first_name,
			self.last_name)
	
	def _get_latest_report(self):
		try:
			return Entry.objects.filter(monitor=self).order_by('-time')[0]
		
		except IndexError:
			return "N/A"

	latest_report = property(_get_latest_report)
	
	
	
	# 'summarize' the field monitor by
	# returning his full name and number
	def _get_details(self):
		ph = self.phone or "unknown"
		return "%s (%s)" % (self, ph)
	details = property(_get_details)


class Supply(models.Model):
	name = models.CharField(max_length=100, unique=True)
	code = models.CharField(max_length=20, unique=True)
	
	class Meta:
		verbose_name_plural="Supplies"

	def __unicode__(self):
		return self.name

	
	def guess(self):
		return [self.name, self.code]
	
	def _get_number_of_reports(self):
		return len(Report.objects.filter(supply=self.id))

	number_of_reports = property(_get_number_of_reports)


class Region(models.Model):
	name = models.CharField(max_length=100, unique=True, help_text="Name of region")

	def __unicode__(self):
		return self.name

	def _get_number_of_zones(self):
		return len(Zone.objects.filter(region=self.id))

	number_of_zones = property(_get_number_of_zones)


class Zone(models.Model):
	name = models.CharField(max_length=100, unique=True, help_text="Name of zone")
	region = models.ForeignKey(Region, help_text="Name of region")
	
	class Meta:
		ordering = ('region', 'name')
	
	def __unicode__(self):
		return self.name

	def _get_number_of_areas(self):
		return len(Area.objects.filter(zone=self.id))

	number_of_woredas = property(_get_number_of_areas)


class Area(models.Model):
	name = models.CharField(max_length=100, unique=True, help_text="Full name of woreda")
	code = models.CharField(max_length=20, unique=True, editable=False)
	zone = models.ForeignKey(Zone, help_text="Name of zone")
	
	def save(self):
		# if this area does not already
		# have a code, assign a new one
		if(self.code == ""):
			c = woreda_code()
			self.code = c
		
		# invoke parent to save data
		models.Model.save(self)
	
	class Meta:
		verbose_name = "Woreda"
		ordering = ['name']
	
	def __unicode__(self):
		#return "%s (%s)" % (self.name, self.code)
		return self.name
	
	def _get_number_of_locations(self):
		return len(Location.objects.filter(area=self.id))
	
	number_of_OTPs = property(_get_number_of_locations)


class Location(models.Model):
	name = models.CharField(max_length=100, help_text="Full name of the OTP")
	code = models.CharField(max_length=20, unique=True, editable=False)
	area = models.ForeignKey(Area, help_text="Name of woreda")
	latitude = models.DecimalField(max_digits=8, decimal_places=6, null=True, blank=True, help_text="The physical latitude of this OTP")
	longitude = models.DecimalField(max_digits=8, decimal_places=6, null=True, blank=True, help_text="The physical longitude of this OTP")
	
	def save(self):
		# if this OTP does not already
		# have a code, assign a new one
		if(self.code == ""):
			c = otp_code()
			self.code = c
		
		# invoke parent to save data
		models.Model.save(self)
	
	class Meta:
		verbose_name = "OTP"
		ordering = ['name']
	
	def __unicode__(self):
		#return "%s (%s)" % (self.name, self.code)
		return self.name

	def _get_woreda(self):
    		return self.area

	woreda = property(_get_woreda)


class SupplyPlace(models.Model):
	supply = models.ForeignKey(Supply)
	location = models.ForeignKey(Location, verbose_name="OTP", blank=True, null=True, help_text="Name of OTP")
	area = models.ForeignKey(Area, verbose_name="Woreda", blank=True, null=True, help_text="Name of Woreda")
	quantity = models.PositiveIntegerField(blank=True, null=True, help_text="Balance at OTP")
	
	def __unicode__(self):
		return "%s at %s (%s)" %\
		(self.supply.name, self.place, self.type)

	class Meta:
		verbose_name_plural="Supplies per OTP or Woreda"
	
	def _get_place(self):
		if self.location: return self.location
		elif self.area:   return self.area
		else:             return "Unknown"
	place = property(_get_place)
	
	def _get_type(self):
		if self.location: return "OTP"
		elif self.area:   return "Woreda"
		else:             return "Unknown"
	type = property(_get_type)
		
	def _get_area(self):
		if self.location: return self.location.area
		elif self.area:   return self.area
		else:             return "Unknown"
	woreda = property(_get_area)


class Notification(models.Model):
	monitor = models.ForeignKey(Monitor)
	time = models.DateTimeField(auto_now_add=True)
	notice = models.CharField(blank=True, max_length=160, help_text="Alert from monitor")
	resolved = models.BooleanField(help_text="Has the alert been attended to?")
	
	def __unicode__(self):
		return "%s by %s" %\
		(self.time.strftime("%d/%m/%y"), self.monitor)


class Report(models.Model):
	supply = models.ForeignKey(Supply)
	begin_date = models.DateField()
	end_date = models.DateField()
	supply_place = models.ForeignKey(SupplyPlace)

	def __unicode__(self):
		return "%s report" % self.supply.name
	
	def _get_latest_entry(self):
		try:
			e = Entry.objects.order_by('-time')[0]
		except:
			e = "No Entries"
		return e
	
	def _get_number_of_entries(self):
		return len(Entry.objects.filter(time__gte=self.begin_date).exclude(time__gte=self.end_date))

	number_of_entries = property(_get_number_of_entries)
	latest_entry = property(_get_latest_entry)
	

class Entry(models.Model):
	monitor = models.ForeignKey(Monitor, help_text="Field monitor")
	supply_place = models.ForeignKey(SupplyPlace, verbose_name="Place", help_text="The OTP or Woreda which this report was sent from")
	time = models.DateTimeField(auto_now_add=True)
	beneficiaries = models.PositiveIntegerField("New Admissions", null=True)
	quantity = models.PositiveIntegerField("Received Quantity", null=True)
	consumption = models.PositiveIntegerField("Consumption", null=True)
	balance = models.PositiveIntegerField("Current Stock Balance", null=True)

	def __unicode__(self):
		return "%s on %s" %\
		(self.supply_place, self.time.strftime("%d/%m/%y"))
	
	class Meta:
		verbose_name_plural="Entries"


class Transaction(models.Model):
	identity = models.PositiveIntegerField(blank=True, null=True)
	
	# the monitor (or number, if monitor isn't known)
	# who triggered the creation of this transaction
	# ----
	# todo: validate that at least one of these is provided
	phone = models.CharField(max_length=30, blank=True, null=True)
	monitor = models.ForeignKey(Monitor, blank=True, null=True)
	
	def __unicode__(self):
		
		# prefer to show a monitor,
		# fall back to phone number
		who = self.monitor
		if who is None:
			who = self.phone
		
		# include the random identity and creator
		return "%s by %s" % (unicode(self.identity), who)


class Message(models.Model):
	transaction = models.ForeignKey(Transaction, blank=True, null=True)
	
	# these are only needed if the message is not bound to a
	# transaction, or the message going out to someone else
	phone = models.CharField(max_length=30, blank=True, null=True)
	monitor = models.ForeignKey(Monitor, blank=True, null=True)
	
	# but every message has these
	time = models.DateTimeField(auto_now_add=True)
	message = models.CharField(max_length=160)
	is_outgoing = models.BooleanField()
	is_virtual = models.BooleanField()
	
	# todo: what is this for? the screen log?
	def __unicode__(self):
		if self.is_outgoing: dir = ">>"
		else:                dir = "<<"
		return "%s %s: %s" % (dir, self.monitor, self.message)

webui/inventory/forms.py
#!/usr/bin/env python
# vim: noet

from django import forms
from models import *
import re

# to match the alias
LOWERCASE_REGEX = re.compile("^[a-z]+$")


class MonitorForm(forms.ModelForm):
	class Meta:
		model = Monitor

	def clean_alias(self):
		data = self.cleaned_data["alias"]
		if not LOWERCASE_REGEX.match(data):
			msg = "This field may only contain lower case letters"
			raise forms.ValidationError(msg)
		
		return data

	
class SupplyForm(forms.ModelForm):
	class Meta:
		model = Supply
	
	def clean_code(self):
		data = self.cleaned_data["code"]
		return data.upper()

webui/export/views.py
from django import http
from django.db import models
from django.utils.text import capfirst
from django.core.exceptions import FieldError


def _get_model(app_label, model_name):
	model = models.get_model(app_label, model_name)
	
	# check that the model is valid
	if model is None:
		raise http.Http404(
		"App %r, model %r, not found."\
		% (app_label, model_name))
	
	return model


def to_excel(request, app_label, model_name, req_filters=None):
	model = _get_model(app_label, model_name)
	max_depth = 8
	rows = []
	
	# if no filters were explictly passed,
	# then we will look for them in the GET
	if req_filters is None:
		req_filters = request.GET
	
	# build a dict of filters, to control
	# which objects we get. todo: is this
	# dangerous? i can't see any way that
	# it is, but it seems kind of wrong
	filters = {}
	for k ,v in req_filters.items():
		filters[str(k)] = v
	
	# fetch the data (might raise if any of the
	# params couldn't be matched to model fields
	try:
		export_data = model.objects.filter(**filters)
	
	except FieldError, e:
		return http.HttpResponse(e.message,
		status=500, mimetype="text/plain")
	
	# sort the records if requested
	if "sort" in req_filters:
		export_data = export_data.order_by(str(req_filters["sort"]))
	
	
	# this function builds a flat list of column titles (verbose names)
	# recursively, to include as much data as possible in the export
	def build_header(model, depth=0, prefix=""):
		columns = []
		
		for field in model._meta.fields:
			caption = prefix + capfirst(field.verbose_name)
			
			# if this field is a foreign key, then
			# we will recurse to fetch it's fields
			if (hasattr(field, "rel")) and (field.rel is not None) and (depth < max_depth):
				columns.extend(build_header(field.rel.to, depth+1, caption + ": "))
				
			# not a foreign key, so append
			# this column in it's raw form
			else:
				columns.append("<th>%s</th>" % (caption))
		
		return columns
	
	
	# the first row contains no data, just field names
	rows.append("<tr>%s</tr>" % ("".join(build_header(model))))
	
	
	
	# this function is *way* too similar to the function
	# above to warrant its independance. abstraction!
	def build_row(model, instance=None, depth=0):
		columns = []
		
		for field in model._meta.fields:
			if instance:
				cell = getattr(instance, field.name)
			
				# if this field is a foreign key, then
				# we will recurse to fetch it's fields
				if (hasattr(field, "rel")) and (field.rel is not None) and (depth < max_depth):
					columns.extend(build_row(field.rel.to, cell, depth+1))
				
				# not a foreign key, so append
				# this column in it's raw form
				else: columns.append("<td>%s</td>" % (cell))
			
			# the instance that we are iterating is
			# none, but we must fill the column, so
			# insert an empty cell
			else: columns.append("<td></td>")
		return columns
	
	
	# the matrix of dumped data
	for object in export_data:
		row = "".join(build_row(model, object))
		rows.append("<tr>%s</tr>" % (row))
	
	
	# dump it as a simple html table
	html = "<table>%s</table>" % ("\n".join(rows))
	
	# download as an excel spreadsheet
	resp = http.HttpResponse(html, mimetype='application/vnd.ms-excel')
	resp["content-disposition"] = "attachment; filename=%s.xls" % model_name
	return resp


def export(request):
	app_label, model_name = request.POST['model'].split("-")
	model = _get_model(app_label, model_name)
	filters = {}
	
	filter_key = "%s-%s-field" % (app_label, model_name)
	field = request.POST[filter_key]
	
	# if an operator was posted, then apply it
	# to the field name, to pass to the django orm
	if "operator" in request.POST:
		op = request.POST["operator"]
		if op != "": field += "__%s" % (op)
	
	filters = {field: request.POST["value"] }
	return to_excel(request, app_label, model_name, filters)

webui/inventory/templates/export-form.html
<div class="export-form module">
	<form action="/export/" method="post">
	<table>
		<caption>Quick Reports</caption>
		<thead>
			<tr>
				<td colspan="4">
					<input type="submit" class="export-button" value="Export" />
					
					Report On:
					<select id="export-form-model" name="model">{% for model in models %}
						<option value="{{ model.app_label }}-{{ model.name }}">{{ model.caption }}</option>{% endfor %}
					</select>
				</td>
			</tr>
			<tr id="export-filter-headers" style="display: none;">
				<th>Filter Field</th>
				<th>Operator</th>
				<th>Value</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<tr style="display: none;">
				<td class="field">{% for model in models %}
					<select class="fields{% if forloop.first %} visible{% endif %} export-fields-{{ model.app_label }}-{{ model.name }}" name="{{ model.app_label }}-{{ model.name }}-field">{% for field in model.fields %}
						<option title="{{ field.help_text }}" value="{{ field.name }}">{{ field.caption }}</option>{% endfor %}
					</select>{% endfor %}
				</td>
				<td>
					<select name="operator">
						<option value="lt">Less Than</option>
						<option value="gt">Greater Than</option>
						<option value="">Equal To</option>
					</select>
				</td>
				<td>
					<input type="text" name="value" size="4" value="" />
				</td>
				<td class="deletelink">
					<span title="Remove this Filter"></span>
				</td>
			</tr>
		</tbody>
		<tfoot>
			<tr>
				<td colspan="4" id="export-add-filter">
					<span class="addlink">Add a Filter</span>
				</td>
			</tr>
		</tfoot>
	</table>
	</form>
</div>
<script type="text/javascript">
	(function() {
		var del_filter = function(e) {
		};
	
		/* hide all field dropdowns, then show the new active ones */
		$("export-form-model").addEvent("change", function(e) {
			$$(".export-form select.fields").removeClass("visible");
			$$(".export-fields-" + e.target.value).addClass("visible");
		});
	
		/* when the "add filter" link is clicked, clone the
		 * first row filters and append it to the end */
		$("export-add-filter").addEvent("click", function(e) {
			var tbody = $$(".export-form tbody")[0];
			tbody.getFirst().clone().setStyle("display", "").inject(tbody);
			
			$("export-filter-headers").setStyle("display", "");
		});
	})();
</script>

webui/inventory/templates/graph.html
<img src="graphs/entries.png" />
<img src="graphs/otps.png" />
<img src="graphs/avg_otps.png" />
<img src="graphs/monitors.png" />

webui/inventory/templates/grid.html
<table>
	<caption>Today's Entries</caption>
	<thead>
		<tr>
			<th scope="column">OTP/Woreda</th>
			<th scope="column">Code</th>
			<th scope="column" class="tip" title="New Admission">NewAd</th>
			<th scope="column" class="tip" title="Quantity Received">Recvd</th>
			<th scope="column" class="tip" title="Consumption">Cons</th>
			<th scope="column" class="tip" title="Current Stock Balance">Bal</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	{% for entry in entries %}
		<tr>
			<th scope="row"><span title="{{ entry.supply_place.type }}">{{ entry.supply_place.place }}</span></td>
			<td>{{ entry.supply_place.place.code }}</td>
			<td>{{ entry.beneficiaries }}</td>
			<td>{{ entry.quantity }}</td>
			<td>{{ entry.consumption }}</td>
			<td>{{ entry.balance }}</td>
			<td><a class="changelink" title="Change this Entry" href="/inventory/entry/{{ entry.pk }}/">Change</a></td>
		</tr>
	{% endfor %}
	</tbody>
</table>

webui/inventory/templates/messages.html
<table>
	<caption>{{ caption }}</caption>
	<thead>
		<tr>
			<th scope="column">Monitor</th>
			<th scope="column">Phone</th>
			<th scope="column">Message</th>
		</tr>
	</thead>
	<tbody>
	{% for m in messages %}
		<tr class="trans-{{ m.transaction }}">
			{% if m.monitor %}<td class="monitor"><a href="/inventory/monitor/{{ m.monitor.pk }}/">{{ m.monitor }}</a>{% else %}<td class="monitor dull">Unknown{% endif %}</td>
			<td class="phone">{{ m.phone }}</td>
			<td class="msg">{{ m.message }}</td>
		</tr>
	{% endfor %}
	</tbody>
</table>

webui/inventory/templates/notifications.html
{% if notifications %}
<div class="notifications module">
	<table>
		<caption>{{ caption }}</caption>
		<thead>
			<tr>
				<th scope="column">Monitor</th>
				<th scope="column">Message</th>
			</tr>
		</thead>
		<tbody>
		{% for n in notifications %}
			<tr>
				<td class="monitor"><a href="/inventory/monitor/{{ n.monitor.pk }}/">{{ n.monitor }}</a></td>
				<td class="msg"><a href="/inventory/notification/{{ n.pk }}/">{{ n.notice }}</a></td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
</div>
{% endif %}

webui/inventory/templates/period.html
Current reporting period:
<span class="start">{{ start|date:"D dS M" }}</span>
to <span class="to">{{ end|date:"D dS M" }}</span>

<!-- {{ start }} - {{ end }} -->

webui/inventory/templates/reference.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">

<html>
	<head>
		<title>All OTPs</title>
		<link rel="stylesheet" href="/assets/css/export.css" />
	</head>
	<body>
		{% for region in regions %}
		<h1><a href="/inventory/region/{{ region.pk }}">{{ region.name }} Region</a></h1>
		<div class="region">
			{% for zone in region.zones %}
			<h2><a href="/inventory/zone/{{ zone.pk }}/">{{ zone.name }} Zone</a></h2>
			<div class="zone">
				{% for area in zone.areas %}{% if area.locations %}
				<table>
					<caption><a href="/inventory/area/{{ area.pk }}/"><span>{{ area.name }} Woreda</span> (<span>{{ area.code }}</span>)</a></caption>
					<tbody>
						{% for location in area.locations %}
						{% if location.left %}<tr>{% endif %}
							{% if location.right %}<td class="gap"></td>{% endif %}
							<th class="{% if location.left %}L{% else %}R{% endif %}"><a href="/inventory/location/{{ location.pk }}/">{{ location.name }}</a></th>
							<td class="{% if location.left %}L{% else %}R{% endif %}">{{ location.code }}</td>
						{% if location.right %}</tr>{% else %}
						{% if forloop.last %}<td class="gap empty"></td><th class="R empty"></th><td class="R empty"></td>{% endif %}
						{% endif %}
						{% endfor %}
					</tbody>
				</table>
				{% endif %}{% endfor %}
			</div>
			{% endfor %}
		</div>
		{% endfor %}
	</body>	
</html>

webui/inventory/templates/send.html
<div class="send module">
	<form action="/send_sms/" method="post">
		<fieldset>
						
			<table>
				<caption>Send a Message to Field Monitor(s)</caption>
				<tbody>
					<tr>
						<td class="form" id="send-form">
							<div class="textarea"><div>
								<textarea name="message"></textarea>
							</div></div>
	
							<input type="submit" id="fm-send-submit" value="Send" />
						</td>
						<td>
							<div class="recipients" id="send-recipients">
								{% for m in monitors %}
								<div>
									<input type="checkbox" value="{{ m.pk }}" id="fm-monitor-{{ m.pk }}" name="monitor-{{ m.pk }}" />
									<label for="fm-monitor-{{ m.pk }}">{{ m }}</label>
								</div>
								{% endfor %}
							</div>
							
							<script type="text/javascript">
								(function() {
									/* set the 'checked' status of all monitors
									 * at once, because there are a lot of them */
									var select_all = function (state) {
										$$("#send-recipients input").each (function(el) {
											el.checked = state;
										});
									};
									
									/* element to hold all/none buttons */
									var container = $("send-recipients");
									var txta = $$("#send-form textarea")[0];
									
									/* ...and the SELECT NONE button */
									new Element ("span", {
										"html": "Select All",
										"class": "sel-all",
										"title": "Select all monitors",
										"events": {
											"click": function (ev) {
												select_all (true);
												txta.focus();
										}}
									}).inject (container, "before");
									
									/* create the SELECT ALL button */
									new Element ("span", {
										"html": "Select None",
										"class": "sel-none",
										"title": "Select no monitors",
										"events": {
											"click": function (ev) {
												select_all (false);
												txta.focus();
										}}
									}).inject (container, "before");
									
									
									/* keep track of the last monitor
									 * link that was clicked, so double-
									 * clicked links can behave normally */
									var last_link = null;
									
									/* watch all clicks for clicks on monitors */
									$(document.body).addEvent ("click", function(ev) {
										var url = "/inventory/monitor/";
										var el = $(ev.target);
										
										if (el.get ("tag") == "a") {
											if (el.get ("href").slice (0, 19) == url) {
												
												/* if this link has already been clicked,
												 * then abort, and follow the link */
												if (last_link == el)
													return true;
												
												/* otherwise, this is the first click,
												 * but note this link for next time */
												el.set ("title", "Click again to follow link");
												last_link = el;	
												
												/* attempt to find a matching monitor checkbox */
												var pk = parseInt(el.get ("href").slice(19, -1));
												var check = $("fm-monitor-" + pk);
												if (check) {
												
													/* unselect all, except for the
													 * monitor that we just clicked on */
													select_all (false);
													check.checked = true;
													
													/* scroll the monitor into view (in
													 * the little recipients window), and
													 * briefly flash the background */
													var div = check.getParent();
													var pos = div.getPosition (container);
													container.scrollTo (0, pos.y);
													div.highlight();
													
													/* put the caret into the message
													 * textarea, so we can click, type,
													 * hit return to send messages */
													txta.focus();
													
													/* cancel the usual event */	
													ev.stop();
												}
											}
										}
									});
									
									/* auto-size the text area to fill the white-space
									 * below it (the recipients list is always higher) */
									$(document).addEvent ("domready", function (ev) {
										var cell_h = $("send-form").getSize().y;
										var but_h  = $("fm-send-submit").getSize().y;
										var rest   = 25; // sum of the padding, margins
										                 // and borders in the cell
										txta.setStyle("height", cell_h - but_h - rest);
									});
								})(); // module
							</script>
						</td>
					</tr>
				</tbody>
			</table>
		</fieldset>
	</form>
</div>

webui/inventory/templates/transactions.html
<table>
	<caption>Recent Transactions</caption>
	<thead>
		<tr>
			<th scope="column">Initiator</th>
			<th scope="column">Messages</th>
		</tr>
	</thead>
	<tbody>
	{% for t in transactions %}
		<tr>
			{% if t.monitor %}<td class="monitor"><a href="/inventory/monitor/{{ t.monitor.pk }}/">{{ t.monitor }}</a>{% else %}{% if t.phone %}<td class="phone">{{ t.phone }}{% else %}<td class="monitor dull">Unknown{% endif %}{% endif %}</td>
			<td class="messages">
				<table>
					{% for m in t.message_set.all %}
					<tr class="{% if m.is_outgoing %}out{% else %}in{% endif %}{% if m.is_virtual %} virtual{% endif %}{% if forloop.first %} first{% endif %}{% if forloop.last %} last{% endif %}">
						<td class="dir"{% if m.is_outgoing %} title="Outgoing">&raquo;{% else %} title="{% if m.is_virtual %}Virtual {% endif %}Incoming">&laquo;{% endif %}</td>
						
						<td class="msg">
							{% if m.monitor %}<span class="to" title="Number: {{ m.monitor.phone }}">To: {{ m.monitor }}</span>{% else %}
							{% if m.phone %}{% ifnotequal t.phone m.phone %}<span class="to">To: {{ m.phone }}</span>{% endifnotequal %}{% endif %}{% endif %}
							<span title="{% if m.is_outgoing %}Sent{% else %}Received{% endif %} at: {{ m.time }}">{{ m.message }}</span>
						</td>
					</tr>
					{% endfor %}
				</table>
			</td>
		</tr>
	{% endfor %}
	</tbody>
</table>